# Generated by Django 4.0.6 on 2022-08-20 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formacao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Formacao_usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Permissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Permissao_usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('matricula', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=20)),
                ('data_nascimento', models.DateField()),
                ('tipo_usuario', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteinfo.tipo_usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(max_length=200)),
                ('texto', models.TextField()),
                ('data_publicacao', models.DateField(auto_now=True)),
                ('categoria', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteinfo.categoria')),
                ('usuario', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteinfo.usuario')),
            ],
        ),
    ]
